version: "3.8"

services:
    mongodb:
        image: mongo
        container_name: mongodb
        environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=admin
        ports:
        - 27017:27017